apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    kubernetes.io/metadata.name: grafana-prod
  name: grafana-prod
spec:
  finalizers:
  - kubernetes
